# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('set_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=40)),
                ('user_pass', models.CharField(max_length=65)),
                ('user_email', models.CharField(max_length=50)),
                ('user_addr', models.CharField(max_length=1000)),
                ('user_code', models.CharField(max_length=20)),
                ('user_tel', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
