# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('set_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('ad_name', models.CharField(max_length=20)),
                ('ad_image', models.ImageField(upload_to='')),
                ('ad_link', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
