# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='ad_image',
            field=models.ImageField(upload_to='ad'),
        ),
    ]
